/**
 * Per-channel game-loop state machine — simplified for on-demand reading.
 *
 * In the on-demand model:
 *   - All blocks are pre-generated before a session goes active.
 *   - No live voting, no phase transitions (reading → voting → resolution → afterparty).
 *   - The game loop only handles session lifecycle: scheduled → active → completed.
 *   - The RealtimeEngine presence-triggered ticker is used only for session start.
 *   - Reading is REST-based (client fetches blocks from /api/blocks/:sessionId).
 *   - Discussion is always-on WebSocket chat, not phase-based.
 */

import { storage } from "../storage";
import { logger } from "../logger";
import { batchGenerateBlocks, getPreviousSessionContext } from "../blocks/batch-generate";
import type { WsMessage, Block, Session } from "@shared/schema";

// ── Types ────────────────────────────────────────────────────────────────────

export type ChannelId = string;

export interface CachedChannelState {
  currentPhase: string;
  phaseEndsAt: Date;
  decisionEndsAt: Date;
  initialTimeToDecision: number;
  turnsToNextChoice: number;
  currentBlockId: number | null;
  activeSessionId: number | null;
}

// ── Timing Constants ────────────────────────────────────────────────────────

/** How long each story block is displayed before auto-advancing (~25s). */
export const READING_SEGMENT_MS = 25_000;

/** 3-minute window before scheduled start where gathering is allowed. */
export const LOBBY_DELAY_MS = 3 * 60 * 1000;
export const START_BEFORE_MS = LOBBY_DELAY_MS;

/**
 * After all blocks are read, the discussion window stays open for 24h
 * (until the next episode drops). This replaces the old 3-minute afterparty.
 */
export const DISCUSSION_WINDOW_MS = 24 * 60 * 60 * 1000;

export const PHASE_INITIAL_MS: Record<string, number> = {
  reading: READING_SEGMENT_MS,
};

// ── In-Memory Caches (no TTL — entries are authoritative until invalidated) ──

const stateCacheStore = new Map<string, CachedChannelState>();

export const stateCache = {
  get: (k: string) => stateCacheStore.get(k),
  set: (k: string, v: CachedChannelState) => stateCacheStore.set(k, v),
  invalidate: (k: string) => stateCacheStore.delete(k),
  keys: () => [...stateCacheStore.keys()],
};

/** Clears cache. Used by tests to reset state between cases. */
export function clearChannelCache(): void {
  stateCacheStore.clear();
}

// ── Session Start ────────────────────────────────────────────────────────────

export async function startSessionForChannelId(
  channelId: ChannelId,
  session: Session,
  broadcast: (channelId: ChannelId, message: WsMessage) => void,
) {
  logger.info(
    `Starting on-demand session "${session.title}" for channel ${channelId}`,
    "session",
  );

  // ── Auto-generate blocks if not pre-generated ───────────────────────────
  // In production, blocks should be pre-generated by the scheduler before the
  // session activates.  If they're missing (e.g. first-ever session or a manual
  // debug start), we generate them on the fly.
  let existingBlocks = await storage.getBlocksBySessionOrdered(session.id);
  if (existingBlocks.length === 0) {
    logger.info(
      `Session ${session.id} has no pre-generated blocks. Auto-generating...`,
      "session",
    );

    // Get narrative context from the previous session for continuity
    const previousContext = await getPreviousSessionContext(channelId, session.id);

    // Fire-and-forget: batch generation happens asynchronously.  The session
    // becomes active immediately so early arrivals can see the lobby; blocks
    // are streamed in as they complete (the client polls /api/blocks/:sessionId).
    batchGenerateBlocks(channelId, session.id, previousContext).catch((err) => {
      logger.error(
        `[Session] Auto-generation failed for session ${session.id}`,
        "session",
        err instanceof Error ? err : new Error(String(err)),
      );
    });

    // No blocks exist yet — set currentBlockId to null; clients will see a
    // "Generating..." state until blocks are available.
  }

  // Re-fetch blocks (in case auto-generation completed synchronously — unlikely
  // but possible in tests or with a mock AI).
  existingBlocks = await storage.getBlocksBySessionOrdered(session.id);

  // ── Activate session ────────────────────────────────────────────────────
  const now = Date.now();
  const phaseEndsAt = new Date(now + READING_SEGMENT_MS);

  await storage.upsertChannelState(channelId, {
    currentPhase: "reading",
    phaseEndsAt,
    decisionEndsAt: phaseEndsAt,
    initialTimeToDecision: 0,
    turnsToNextChoice: 0,
    currentBlockId: existingBlocks[0]?.id ?? null,
    activeSessionId: session.id,
  });

  stateCache.set(channelId, {
    currentPhase: "reading",
    phaseEndsAt,
    decisionEndsAt: phaseEndsAt,
    initialTimeToDecision: 0,
    turnsToNextChoice: 0,
    currentBlockId: existingBlocks[0]?.id ?? null,
    activeSessionId: session.id,
  });

  await storage.updateSessionStatus(session.id, "active");

  broadcast(channelId, {
    type: "SESSION_STATUS",
    payload: { status: "active", session },
  });
}

// ── Per-Channel Tick ─────────────────────────────────────────────────────────

/**
 * Processes one tick for a single channel.
 *
 * In the on-demand model, this is minimal: it mainly handles starting
 * scheduled sessions and marking them completed when the discussion window
 * expires. Client-driven reading (block fetch, auto-advance) is handled
 * entirely on the client side via REST.
 */
export async function handleChannelTick(
  channelId: ChannelId,
  now: number,
  broadcast: (channelId: ChannelId, message: WsMessage) => void,
  startSession: (
    channelId: ChannelId,
    session: Session,
    broadcast: (channelId: ChannelId, message: WsMessage) => void,
  ) => Promise<void>,
): Promise<{ continue: boolean }> {
  try {
    let dbState = stateCache.get(channelId);

    if (!dbState) {
      const raw = await storage.getChannelState(channelId);
      if (raw) {
        const cachedState: CachedChannelState = {
          currentPhase: raw.currentPhase,
          phaseEndsAt: raw.phaseEndsAt,
          decisionEndsAt: raw.decisionEndsAt,
          initialTimeToDecision: raw.initialTimeToDecision,
          turnsToNextChoice: raw.turnsToNextChoice,
          currentBlockId: raw.currentBlockId,
          activeSessionId: raw.activeSessionId,
        };
        stateCache.set(channelId, cachedState);
        dbState = cachedState;
      }
    }

    // ── Handle Inactive / Scheduled Channels ─────────────────────────────
    if (!dbState?.activeSessionId) {
      const next = await storage.getNextSession(channelId);

      if (next) {
        const startThreshold =
          next.scheduledStart.getTime() - START_BEFORE_MS;
        if (now >= startThreshold) {
          const isGameLoopLockAcquired = await storage.tryAcquireGameLock(
            channelId,
            30_000,
          );
          if (!isGameLoopLockAcquired) return { continue: false };

          try {
            await startSession(channelId, next, broadcast);
          } catch (err) {
            logger.error(
              `Failed to start session: ${err instanceof Error ? err.message : String(err)}`,
            );
          } finally {
            await storage.releaseGameLock(channelId);
          }
        }
      }

      return { continue: false };
    }

    const activeSession = await storage.getSessionById(
      dbState.activeSessionId,
    );
    if (!activeSession) {
      await storage.upsertChannelState(channelId, {
        activeSessionId: null,
        currentBlockId: null,
      });
      return { continue: false };
    }

    // ── Session expired: mark as completed ───────────────────────────────
    // In the on-demand model, the session stays "active" until the
    // discussion window expires (scheduledEnd).
    if (now >= activeSession.scheduledEnd.getTime()) {
      const locked = await storage.tryAcquireGameLock(channelId, 10_000);
      if (!locked) return { continue: true };

      try {
        logger.info(
          `Ending session "${activeSession.title}" for channel ${channelId} after discussion window.`,
          "session",
        );
        await storage.updateSessionStatus(activeSession.id, "completed");
        await storage.upsertChannelState(channelId, {
          activeSessionId: null,
          currentBlockId: null,
          currentPhase: "reading",
        });

        stateCache.invalidate(channelId);

        broadcast(channelId, {
          type: "SESSION_STATUS",
          payload: { status: "completed", session: activeSession },
        });
      } finally {
        await storage.releaseGameLock(channelId);
      }
      return { continue: false };
    }

    return { continue: true };
  } catch (err) {
    logger.error(
      `Unhandled error in game loop for channel ${channelId}`,
      "gameloop",
      err instanceof Error ? err : new Error(String(err)),
    );
    return { continue: true };
  }
}
