import crypto from "node:crypto";
import { generateUUID } from "@portalshq/capability-realtime-fanout";
import type { QueueUploadAsset } from "@portalshq/capability-queue-broadcast";
import type { Block, DeliverySegment, Session } from "@shared/schema";

import { generateStoryBlock } from "../blocks/ai";
import type { SelectedImageRepresentation } from "../blocks/image-references";
import {
  archiveStoryImage,
  downloadArchiveBuffer,
  generateStoryImageAsset,
  type GeneratedStoryImage,
} from "../image-uploader";
import { logger } from "../logger";
import {
  archiveSpeechBuffer,
  synthesizeNarrationBuffers,
  type SpeechBuffer,
} from "../media/tts-service";
import { storage } from "../storage";

/** One logical turn. Its image and optional narration are staged independently. */
export interface PreparedBroadcastSlot {
  /** Real audio duration, or the configured duration for an image-only turn. */
  durationSeconds: number;
  /** Deterministic item prefix, retained for legacy receipt reconciliation. */
  idempotencyPrefix: string;
  /** The Streamer slot identity shared by all successful assets in this turn. */
  slotKey: string;
  blockId?: number;
  segmentOrdinal: number;
  /** Legacy atomic-pair receipt from sessions created before slot support. */
  queuePairId?: string;
  /** Individual staged Streamer job receipts. */
  imageJobId?: string;
  audioJobId?: string;
  /** Present only while this trusted backend holds fresh generated bytes. */
  image?: QueueUploadAsset;
  audio?: QueueUploadAsset;
}

/** Ambient media keeps its shared image once until it is staged for each segment. */
export interface PreparedAmbientTurn {
  sequence: number;
  idempotencyPrefix: string;
  /**
   * Distinct visual identity for buffer accounting. Split narration segments
   * share one image (and one contentId); different generations must differ.
   * Media-agnostic by design: a future video turn would carry its own
   * contentId here so image/audio/video all have equal citizenship in the
   * staged-or-released buffer. Optional for backward compatibility — the
   * pipeline falls back to the generation idempotency prefix when absent.
   */
  contentId?: string;
  image: QueueUploadAsset;
  /** Reserved for a future first-class video primitive; never derived from imageDuration. */
  video?: QueueUploadAsset;
  segments: PreparedAmbientSegment[];
  totalDurationSeconds: number;
  totalBytes: number;
}

export interface PreparedAmbientSegment {
  segmentOrdinal: number;
  durationSeconds: number;
  audio?: QueueUploadAsset;
}

interface GeneratedImageWithArchive {
  image: GeneratedStoryImage;
  archiveUrl?: string;
}

interface PreparedNarration {
  text: string;
  speech: SpeechBuffer;
}

const GENERATION_ATTEMPTS = 3;
const RETRY_DELAYS_MS = [500, 1_500];

/**
 * Generate one canonical turn. Text comes first; image and speech are then
 * independently retried. A successful image survives a failed TTS attempt as
 * a short image-only slot. A successful audio asset is deliberately discarded
 * when no image exists, matching the ebook's presentation policy.
 */
export async function prepareCanonicalSlot(
  channelId: string,
  session: Session,
  previousContext: string,
  signal: AbortSignal,
  useEmbedding?: boolean,
): Promise<{ block?: Block; slots: PreparedBroadcastSlot[] }> {
  const generated = await prepareCanonicalText(channelId, previousContext, session.id, signal);
  return finishCanonicalSlot(channelId, session, generated, signal, useEmbedding);
}

/** Narrative text for one canonical turn. Serial and chained: each turn's text needs the previous turn's content. */
export type CanonicalText = Awaited<ReturnType<typeof generateStoryBlock>>;

export function prepareCanonicalText(
  channelId: string,
  previousContext: string,
  sessionId: number | undefined,
  signal: AbortSignal,
): Promise<CanonicalText> {
  signal.throwIfAborted();
  return retryGeneration(
    "narrative text",
    () => generateStoryBlock(channelId, previousContext, false, sessionId),
    signal,
  );
}

/**
 * Media, archive, persistence, and stage-ready slots for already-generated
 * text. Safe to run while the NEXT turn's text generates: it touches only
 * this turn's assets plus one new block row.
 */
export async function finishCanonicalSlot(
  channelId: string,
  session: Session,
  generated: CanonicalText,
  signal: AbortSignal,
  useEmbedding?: boolean,
): Promise<{ block?: Block; slots: PreparedBroadcastSlot[] }> {
  signal.throwIfAborted();
  const imageRepresentations = generated.imageRepresentations ?? generated.selectedImageRepresentations ?? [];
  const media = await generateTurnMedia(channelId, generated.title, generated.content, generated.dialogue, "block", signal, imageRepresentations);
  if (!media.image) return { slots: [] };

  // Slots stage from in-memory bytes; archives are only for DB persistence.
  // Run image + audio archives concurrently so neither blocks the other.
  const imageArchivePromise = media.image.archiveUrl
    ? Promise.resolve(media.image.archiveUrl)
    : archiveStoryImage(media.image.image, channelId, "block");
  const audioArchivePromises = media.narration.map(async ({ speech }, ordinal) => ({
    audioUrl: assertArchiveMediaUrl(
      await archiveSpeechBuffer(
        speech,
        `channel-${channelId}-session-${session.id}-${generateUUID()}-${String(ordinal).padStart(3, "0")}.${speech.extension}`,
      ),
      "audio",
    ),
    // Persist the playout duration, not the raw TTS length: short clips hold
    // the unified image floor so the picture does not vanish after 5-10s.
    // Longer narration is preserved verbatim (never truncated to the floor).
    durationSeconds: slotDurationForSpeech(speech.durationSeconds),
    ordinal,
  }));
  const [imageUrl, archivedSegments] = await Promise.all([
    imageArchivePromise,
    Promise.all(audioArchivePromises),
  ]);
  const deliverySegments: DeliverySegment[] = archivedSegments.length > 0
    ? archivedSegments
    : [{ durationSeconds: imageOnlyDuration(), ordinal: 0 }];
  const blockData = {
    channelId,
    sessionId: session.id,
    title: generated.title,
    content: generated.content,
    dialogue: generated.dialogue ?? null,
    imageUrl: assertArchiveMediaUrl(imageUrl, "image"),
    optionA: generated.optionA ?? null,
    optionB: generated.optionB ?? null,
    ttsEnabled: archivedSegments.length > 0,
    audioUrl: archivedSegments[0]?.audioUrl ?? null,
    deliverySegments,
    isNotable: false,
  };
  const block = useEmbedding !== undefined
    ? await storage.createBlock(blockData, useEmbedding)
    : await storage.createBlock(blockData);
  return {
    block,
    slots: slotsWithAssets({
      channelId,
      sessionId: session.id,
      blockId: block.id,
      image: media.image.image,
      narration: media.narration,
    }),
  };
}

/** Generate a non-canonical ambient turn without archiving or changing narrative context. */
export async function prepareAmbientSlots(
  channelId: string,
  previousCanonicalContext: string,
  runId: string,
  sequence: number,
  signal: AbortSignal,
): Promise<PreparedAmbientTurn | undefined> {
  signal.throwIfAborted();
  let generated: Awaited<ReturnType<typeof generateStoryBlock>>;
  try {
    generated = await retryGeneration(
      "ambient narrative text",
      () => generateStoryBlock(channelId, previousCanonicalContext, false),
      signal,
    );
  } catch (cause) {
    // Ambient is deliberately non-canonical. A provider failure should not
    // blank the stream when the channel already has an archived image that
    // generateImageWithFallback can reuse.
    logger.warn(
      `Ambient narrative unavailable for ${channelId}; attempting an image-only fallback turn`,
      "broadcast",
      asError(cause),
    );
    generated = {
      title: "Ambient interlude",
      content: previousCanonicalContext.trim().slice(0, 300) || "A quiet ambient scene between chapters.",
      dialogue: undefined,
    };
  }
  const ambientReferences = generated.imageRepresentations ?? generated.selectedImageRepresentations ?? [];
  const media = await generateTurnMedia(channelId, generated.title, generated.content, generated.dialogue, "ambient", signal, ambientReferences);
  if (!media.image) return undefined;
  const idempotencyPrefix = `channel:${channelId}:run:${runId}:sequence:${sequence}`;
  const image = toUploadAsset(
    media.image.image.buffer,
    media.image.image.mimeType,
    media.image.image.filename,
  );
  const narration = media.narration.length > 0 ? media.narration : [undefined];
  const segments = narration.map((item, segmentOrdinal) => ({
    segmentOrdinal,
    // Unified image floor: max(config, audio). Short voice clips hold the
    // image for the full floor; long narration is never cut to fit it.
    // Video (when present) keeps its intrinsic duration elsewhere — this
    // floor only ever feeds imageDuration, never a video duration.
    durationSeconds: slotDurationForSpeech(item?.speech.durationSeconds),
    ...(item ? {
      audio: toUploadAsset(item.speech.buffer, item.speech.mimeType, `narration-${segmentOrdinal}.${item.speech.extension}`),
    } : {}),
  }));
  return {
    sequence,
    idempotencyPrefix,
    contentId: idempotencyPrefix,
    image,
    segments,
    totalDurationSeconds: segments.reduce((total, segment) => total + segment.durationSeconds, 0),
    totalBytes: image.data.size + segments.reduce((total, segment) => total + (segment.audio?.data.size ?? 0), 0),
  };
}

/** Reconstruct staged or recoverable slots from canonical delivery metadata. */
export function slotsFromBlock(block: Block): PreparedBroadcastSlot[] {
  const segments = block.deliverySegments ?? (
    block.audioUrl ? [{ audioUrl: block.audioUrl, durationSeconds: 25, ordinal: 0 }] : []
  );
  return segments.map((segment) => {
    const idempotencyPrefix = segment.queueIdempotencyKey
      ?? `channel:${block.channelId}:session:${block.sessionId}:block:${block.id}:segment:${segment.ordinal}`;
    return {
      durationSeconds: segment.durationSeconds,
      idempotencyPrefix,
      slotKey: segment.queueSlotKey ?? `${idempotencyPrefix}:slot`,
      blockId: block.id,
      segmentOrdinal: segment.ordinal,
      ...(segment.queuePairId ? { queuePairId: segment.queuePairId } : {}),
      ...(segment.queueImageJobId ? { imageJobId: segment.queueImageJobId } : {}),
      ...(segment.queueAudioJobId ? { audioJobId: segment.queueAudioJobId } : {}),
    };
  });
}

/** Recovery-only: reload archived assets after a process restart interrupted staging. */
export async function hydrateCanonicalSlot(
  block: Block,
  slot: PreparedBroadcastSlot,
  signal: AbortSignal,
): Promise<PreparedBroadcastSlot> {
  if (!block.imageUrl) throw new Error(`Canonical block ${block.id} has no archived image`);
  const segment = block.deliverySegments?.find((item) => item.ordinal === slot.segmentOrdinal)
    ?? (block.audioUrl ? { audioUrl: block.audioUrl, durationSeconds: slot.durationSeconds, ordinal: slot.segmentOrdinal } : undefined);
  if (!segment) throw new Error(`Canonical block ${block.id} has no delivery segment`);
  const image = await fetchArchiveAsset(assertArchiveMediaUrl(block.imageUrl, "image"), "image", signal);
  const audio = segment.audioUrl
    && !segment.queueAudioUnavailable
    ? await fetchArchiveAsset(assertArchiveMediaUrl(segment.audioUrl, "audio"), "audio", signal)
    : undefined;
  return { ...slot, image, ...(audio ? { audio } : {}) };
}

async function generateTurnMedia(
  channelId: string,
  title: string,
  content: string,
  dialogue: string | null | undefined,
  imageType: "block" | "ambient",
  signal: AbortSignal,
  imageRepresentations: readonly SelectedImageRepresentation[] = [],
): Promise<{ image?: GeneratedImageWithArchive; narration: PreparedNarration[] }> {
  const description = `${title}: ${content.slice(0, 300)}`;
  // Image and narration generate concurrently. Narration is best-effort: a
  // single failed attempt falls back to an image-only turn (playback must
  // proceed identically with or without narration), so it defaults to one
  // attempt while text/image keep the fuller retry budget.
  const [imageResult, narrationResult] = await Promise.allSettled([
    retryGeneration("story image", () => generateImageWithFallback(description, channelId, imageType, signal, imageRepresentations), signal),
    retryGeneration("narration", () => synthesizeNarrationBuffers(dialogue || content, {
      maxDurationSeconds: Number(process.env.BROADCAST_MAX_SEGMENT_SECONDS || 25),
      signal,
    }), signal, narrationAttempts()),
  ]);
  if (imageResult.status === "rejected") {
    logger.error(
      `Skipping ${imageType} turn for ${channelId}: image generation exhausted retries`,
      "broadcast",
      asError(imageResult.reason),
    );
    if (narrationResult.status === "fulfilled" && narrationResult.value.length > 0) {
      logger.warn(`Discarding lone narration for ${channelId}: image generation failed`, "broadcast");
    }
    return { narration: [] };
  }
  if (narrationResult.status === "rejected" || narrationResult.value.length === 0) {
    logger.warn(
      `Narration unavailable for ${channelId}; releasing image-only turn`,
      "broadcast",
      narrationResult.status === "rejected" ? asError(narrationResult.reason) : undefined,
    );
    return { image: imageResult.value, narration: [] };
  }
  return { image: imageResult.value, narration: narrationResult.value };
}

function slotsWithAssets(input: {
  channelId: string;
  sessionId?: number;
  blockId?: number;
  runId?: string;
  sequence?: number;
  image: GeneratedStoryImage;
  narration: PreparedNarration[];
}): PreparedBroadcastSlot[] {
  const base = input.blockId !== undefined && input.sessionId !== undefined
    ? `channel:${input.channelId}:session:${input.sessionId}:block:${input.blockId}`
    : `channel:${input.channelId}:run:${input.runId}:sequence:${input.sequence}`;
  const narration = input.narration.length > 0 ? input.narration : [undefined];
  return narration.map((item, segmentOrdinal) => {
    const idempotencyPrefix = `${base}:segment:${segmentOrdinal}`;
    return {
      durationSeconds: slotDurationForSpeech(item?.speech.durationSeconds),
      idempotencyPrefix,
      slotKey: `${idempotencyPrefix}:slot`,
      ...(input.blockId !== undefined ? { blockId: input.blockId } : {}),
      segmentOrdinal,
      image: toUploadAsset(input.image.buffer, input.image.mimeType, input.image.filename),
      ...(item ? {
        audio: toUploadAsset(item.speech.buffer, item.speech.mimeType, `narration-${segmentOrdinal}.${item.speech.extension}`),
      } : {}),
    };
  });
}

async function generateImageWithFallback(
  description: string,
  channelId: string,
  imageType: "block" | "ambient",
  signal: AbortSignal,
  imageRepresentations: readonly SelectedImageRepresentation[] = [],
): Promise<GeneratedImageWithArchive> {
  try {
    return { image: await generateStoryImageAsset(description, { imageRepresentations, signal }) };
  } catch (cause) {
    logger.warn(
      `Generated image failed for ${channelId}; trying an existing channel image`,
      "broadcast",
      asError(cause),
    );
    signal.throwIfAborted();
    const fallback = await storage.getRandomImage(channelId);
    if (!fallback) throw cause;
    const asset = await fetchArchiveAsset(assertArchiveMediaUrl(fallback, "image"), "image", signal);
    return {
      image: {
        buffer: Buffer.from(await asset.data.arrayBuffer()),
        mimeType: "image/jpeg",
        filename: asset.filename,
      },
      ...(imageType === "block" ? { archiveUrl: fallback } : {}),
    };
  }
}

async function retryGeneration<T>(
  label: string,
  operation: () => Promise<T>,
  signal: AbortSignal,
  attempts: number = GENERATION_ATTEMPTS,
): Promise<T> {
  const bounded = Math.max(1, Math.min(GENERATION_ATTEMPTS, Math.floor(attempts) || 1));
  let lastError: unknown;
  for (let attempt = 0; attempt < bounded; attempt += 1) {
    signal.throwIfAborted();
    try {
      return await operation();
    } catch (cause) {
      if (signal.aborted) throw signal.reason;
      lastError = cause;
      if (attempt === bounded - 1) break;
      logger.warn(`${label} attempt ${attempt + 1} failed; retrying`, "broadcast", asError(cause));
      await wait(RETRY_DELAYS_MS[attempt]!, signal);
    }
  }
  throw asError(lastError);
}

/**
 * How many times a failed narration (TTS) attempt is retried before falling
 * back to an image-only turn. Defaults to 1 — a dead provider (e.g. exhausted
 * quota) must not stall staging behind doomed retries. Raise via
 * BROADCAST_NARRATION_ATTEMPTS (1-3) if transient TTS flakes are common.
 */
function narrationAttempts(): number {
  const raw = process.env.BROADCAST_NARRATION_ATTEMPTS;
  if (!raw?.trim()) return 1;
  const value = Number(raw);
  if (!Number.isInteger(value)) return 1;
  return Math.max(1, Math.min(GENERATION_ATTEMPTS, value));
}

/**
 * Playout floor for narrated turns: max(config, narration length). Short TTS
 * holds the picture for the full floor instead of vanishing after 5-10s;
 * long narration is preserved verbatim. This value only ever feeds
 * `imageDuration` on image uploads — video uploads must omit `imageDuration`
 * and keep their intrinsic duration (equal citizenship, no override).
 */
function broadcastImageFloor(): number {
  const configured = Number(process.env.BROADCAST_IMAGE_DURATION_SECONDS ?? 12);
  return Number.isFinite(configured) ? Math.max(1, Math.min(30, configured)) : 12;
}

/**
 * Image-only turns (narration unavailable) hold longer than the narrated
 * floor: with no audio pacing the turn, the still should cover a full
 * generation cycle or consumption outruns production and images blink.
 * Tunable via BROADCAST_IMAGE_ONLY_DURATION_SECONDS (default 15).
 */
function imageOnlyDuration(): number {
  const configured = Number(process.env.BROADCAST_IMAGE_ONLY_DURATION_SECONDS ?? 15);
  return Number.isFinite(configured) ? Math.max(1, Math.min(30, configured)) : 15;
}

/** max(floor, speech) — the stored slot duration for one segment. */
function slotDurationForSpeech(speechDurationSeconds?: number): number {
  if (speechDurationSeconds === undefined) return imageOnlyDuration();
  const floor = broadcastImageFloor();
  if (!Number.isFinite(speechDurationSeconds)) return floor;
  return Math.max(floor, speechDurationSeconds);
}

function toUploadAsset(buffer: Buffer, mimeType: string, filename: string): QueueUploadAsset {
  if (buffer.length === 0) throw new Error(`Cannot queue empty ${filename}`);
  return {
    data: new Blob([Uint8Array.from(buffer)], { type: mimeType }),
    filename,
    sha256: crypto.createHash("sha256").update(buffer).digest("hex"),
  };
}

async function fetchArchiveAsset(
  url: string,
  kind: "image" | "audio",
  signal: AbortSignal,
): Promise<QueueUploadAsset> {
  const response = await fetch(url, { signal });
  if (response.ok) {
    const buffer = Buffer.from(await response.arrayBuffer());
    const contentType = response.headers.get("content-type") || (kind === "image" ? "image/jpeg" : "audio/wav");
    return toUploadAsset(buffer, contentType, `recovered-${generateUUID()}.${kind === "image" ? "jpg" : "wav"}`);
  }
  if (response.status === 403) {
    // GCS serves objects stored without a public ACL as 403 over plain HTTPS.
    // Those are exactly the archive URLs this app persisted historically, so a
    // raw 403 here would wedge canonical recovery on the same slot forever
    // (see the "Skipping failed broadcast segment" loop). Fall back to an
    // authenticated SDK read, which succeeds regardless of object ACLs.
    // Steady-state playout never touches archives — this path only runs for
    // post-restart recovery and the archived-image fallback.
    const buffer = await downloadArchiveBuffer(url);
    if (buffer && buffer.length > 0) {
      logger.warn(
        `Archived ${kind} required an authenticated read (public fetch 403); recovered via storage SDK`,
        "broadcast",
      );
      const contentType = kind === "image" ? "image/jpeg" : "audio/wav";
      return toUploadAsset(buffer, contentType, `recovered-${generateUUID()}.${kind === "image" ? "jpg" : "wav"}`);
    }
  }
  throw new Error(`Archived ${kind} download failed (${response.status})`);
}

function assertArchiveMediaUrl(value: string, kind: string): string {
  const url = new URL(value);
  if (url.protocol !== "https:" && (process.env.NODE_ENV === "production" || url.protocol !== "http:")) {
    throw new Error(`${kind} archive URL must use public HTTPS`);
  }
  if (url.username || url.password || url.hash) throw new Error(`${kind} archive URL is not public-safe`);
  return url.toString();
}

function wait(delayMs: number, signal: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    if (signal.aborted) {
      reject(signal.reason);
      return;
    }
    const timer = setTimeout(() => {
      signal.removeEventListener("abort", abort);
      resolve();
    }, delayMs);
    timer.unref?.();
    const abort = () => {
      clearTimeout(timer);
      reject(signal.reason);
    };
    signal.addEventListener("abort", abort, { once: true });
  });
}

function asError(cause: unknown): Error {
  return cause instanceof Error ? cause : new Error(String(cause));
}
