import crypto from "node:crypto";

import type { QueueUploadAsset } from "@portalshq/capability-queue-broadcast";
import type { Block, DeliverySegment, Session } from "@shared/schema";

import { generateStoryBlock } from "../blocks/ai";
import type { SelectedImageRepresentation } from "../blocks/image-references";
import {
  archiveStoryImage,
  generateStoryImageAsset,
  type GeneratedStoryImage,
} from "../image-uploader";
import { logger } from "../logger";
import {
  archiveSpeechBuffer,
  synthesizeNarrationBuffers,
  type SpeechBuffer,
} from "../media/tts-service";
import { storage } from "../storage";

/** One logical turn. Its image and optional narration are staged independently. */
export interface PreparedBroadcastSlot {
  /** Real audio duration, or the configured duration for an image-only turn. */
  durationSeconds: number;
  /** Deterministic item prefix, retained for legacy receipt reconciliation. */
  idempotencyPrefix: string;
  /** The Streamer slot identity shared by all successful assets in this turn. */
  slotKey: string;
  blockId?: number;
  segmentOrdinal: number;
  /** Legacy atomic-pair receipt from sessions created before slot support. */
  queuePairId?: string;
  /** Individual staged Streamer job receipts. */
  imageJobId?: string;
  audioJobId?: string;
  /** Present only while this trusted backend holds fresh generated bytes. */
  image?: QueueUploadAsset;
  audio?: QueueUploadAsset;
}

/** Ambient media keeps its shared image once until it is staged for each segment. */
export interface PreparedAmbientTurn {
  sequence: number;
  idempotencyPrefix: string;
  image: QueueUploadAsset;
  segments: PreparedAmbientSegment[];
  totalDurationSeconds: number;
  totalBytes: number;
}

export interface PreparedAmbientSegment {
  segmentOrdinal: number;
  durationSeconds: number;
  audio?: QueueUploadAsset;
}

interface GeneratedImageWithArchive {
  image: GeneratedStoryImage;
  archiveUrl?: string;
}

interface PreparedNarration {
  text: string;
  speech: SpeechBuffer;
}

const GENERATION_ATTEMPTS = 3;
const RETRY_DELAYS_MS = [500, 1_500];

/**
 * Generate one canonical turn. Text comes first; image and speech are then
 * independently retried. A successful image survives a failed TTS attempt as
 * a short image-only slot. A successful audio asset is deliberately discarded
 * when no image exists, matching the ebook's presentation policy.
 */
export async function prepareCanonicalSlot(
  channelId: string,
  session: Session,
  previousContext: string,
  signal: AbortSignal,
): Promise<{ block?: Block; slots: PreparedBroadcastSlot[] }> {
  signal.throwIfAborted();
  const generated = await retryGeneration(
    "narrative text",
    () => generateStoryBlock(channelId, previousContext, false, session.id),
    signal,
  );
  const imageRepresentations = generated.imageRepresentations ?? generated.selectedImageRepresentations ?? [];
  const media = await generateTurnMedia(channelId, generated.title, generated.content, generated.dialogue, "block", signal, imageRepresentations);
  if (!media.image) return { slots: [] };

  const imageUrl = media.image.archiveUrl
    ?? await archiveStoryImage(media.image.image, channelId, "block");
  const archivedSegments = await Promise.all(media.narration.map(async ({ speech }, ordinal) => ({
    audioUrl: assertArchiveMediaUrl(
      await archiveSpeechBuffer(
        speech,
        `channel-${channelId}-session-${session.id}-${crypto.randomUUID()}-${String(ordinal).padStart(3, "0")}.${speech.extension}`,
      ),
      "audio",
    ),
    durationSeconds: speech.durationSeconds,
    ordinal,
  })));
  const deliverySegments: DeliverySegment[] = archivedSegments.length > 0
    ? archivedSegments
    : [{ durationSeconds: imageOnlyDuration(), ordinal: 0 }];
  const block = await storage.createBlock({
    channelId,
    sessionId: session.id,
    title: generated.title,
    content: generated.content,
    dialogue: generated.dialogue ?? null,
    imageUrl: assertArchiveMediaUrl(imageUrl, "image"),
    optionA: generated.optionA ?? null,
    optionB: generated.optionB ?? null,
    ttsEnabled: archivedSegments.length > 0,
    audioUrl: archivedSegments[0]?.audioUrl ?? null,
    deliverySegments,
    isNotable: false,
  });
  return {
    block,
    slots: slotsWithAssets({
      channelId,
      sessionId: session.id,
      blockId: block.id,
      image: media.image.image,
      narration: media.narration,
    }),
  };
}

/** Generate a non-canonical ambient turn without archiving or changing narrative context. */
export async function prepareAmbientSlots(
  channelId: string,
  previousCanonicalContext: string,
  runId: string,
  sequence: number,
  signal: AbortSignal,
): Promise<PreparedAmbientTurn | undefined> {
  signal.throwIfAborted();
  let generated: Awaited<ReturnType<typeof generateStoryBlock>>;
  try {
    generated = await retryGeneration(
      "ambient narrative text",
      () => generateStoryBlock(channelId, previousCanonicalContext, false),
      signal,
    );
  } catch (cause) {
    // Ambient is deliberately non-canonical. A provider failure should not
    // blank the stream when the channel already has an archived image that
    // generateImageWithFallback can reuse.
    logger.warn(
      `Ambient narrative unavailable for ${channelId}; attempting an image-only fallback turn`,
      "broadcast",
      asError(cause),
    );
    generated = {
      title: "Ambient interlude",
      content: previousCanonicalContext.trim().slice(0, 300) || "A quiet ambient scene between chapters.",
      dialogue: undefined,
    };
  }
  const ambientReferences = generated.imageRepresentations ?? generated.selectedImageRepresentations ?? [];
  const media = await generateTurnMedia(channelId, generated.title, generated.content, generated.dialogue, "ambient", signal, ambientReferences);
  if (!media.image) return undefined;
  const idempotencyPrefix = `channel:${channelId}:run:${runId}:sequence:${sequence}`;
  const image = toUploadAsset(
    media.image.image.buffer,
    media.image.image.mimeType,
    media.image.image.filename,
  );
  const narration = media.narration.length > 0 ? media.narration : [undefined];
  const segments = narration.map((item, segmentOrdinal) => ({
    segmentOrdinal,
    durationSeconds: item?.speech.durationSeconds ?? imageOnlyDuration(),
    ...(item ? {
      audio: toUploadAsset(item.speech.buffer, item.speech.mimeType, `narration-${segmentOrdinal}.${item.speech.extension}`),
    } : {}),
  }));
  return {
    sequence,
    idempotencyPrefix,
    image,
    segments,
    totalDurationSeconds: segments.reduce((total, segment) => total + segment.durationSeconds, 0),
    totalBytes: image.data.size + segments.reduce((total, segment) => total + (segment.audio?.data.size ?? 0), 0),
  };
}

/** Reconstruct staged or recoverable slots from canonical delivery metadata. */
export function slotsFromBlock(block: Block): PreparedBroadcastSlot[] {
  const segments = block.deliverySegments ?? (
    block.audioUrl ? [{ audioUrl: block.audioUrl, durationSeconds: 25, ordinal: 0 }] : []
  );
  return segments.map((segment) => {
    const idempotencyPrefix = segment.queueIdempotencyKey
      ?? `channel:${block.channelId}:session:${block.sessionId}:block:${block.id}:segment:${segment.ordinal}`;
    return {
      durationSeconds: segment.durationSeconds,
      idempotencyPrefix,
      slotKey: segment.queueSlotKey ?? `${idempotencyPrefix}:slot`,
      blockId: block.id,
      segmentOrdinal: segment.ordinal,
      ...(segment.queuePairId ? { queuePairId: segment.queuePairId } : {}),
      ...(segment.queueImageJobId ? { imageJobId: segment.queueImageJobId } : {}),
      ...(segment.queueAudioJobId ? { audioJobId: segment.queueAudioJobId } : {}),
    };
  });
}

/** Recovery-only: reload archived assets after a process restart interrupted staging. */
export async function hydrateCanonicalSlot(
  block: Block,
  slot: PreparedBroadcastSlot,
  signal: AbortSignal,
): Promise<PreparedBroadcastSlot> {
  if (!block.imageUrl) throw new Error(`Canonical block ${block.id} has no archived image`);
  const segment = block.deliverySegments?.find((item) => item.ordinal === slot.segmentOrdinal)
    ?? (block.audioUrl ? { audioUrl: block.audioUrl, durationSeconds: slot.durationSeconds, ordinal: slot.segmentOrdinal } : undefined);
  if (!segment) throw new Error(`Canonical block ${block.id} has no delivery segment`);
  const image = await fetchArchiveAsset(assertArchiveMediaUrl(block.imageUrl, "image"), "image", signal);
  const audio = segment.audioUrl
    ? await fetchArchiveAsset(assertArchiveMediaUrl(segment.audioUrl, "audio"), "audio", signal)
    : undefined;
  return { ...slot, image, ...(audio ? { audio } : {}) };
}

async function generateTurnMedia(
  channelId: string,
  title: string,
  content: string,
  dialogue: string | null | undefined,
  imageType: "block" | "ambient",
  signal: AbortSignal,
  imageRepresentations: readonly SelectedImageRepresentation[] = [],
): Promise<{ image?: GeneratedImageWithArchive; narration: PreparedNarration[] }> {
  const description = `${title}: ${content.slice(0, 300)}`;
  const [imageResult, narrationResult] = await Promise.allSettled([
    retryGeneration("story image", () => generateImageWithFallback(description, channelId, imageType, signal, imageRepresentations), signal),
    retryGeneration("narration", () => synthesizeNarrationBuffers(dialogue || content, {
      maxDurationSeconds: Number(process.env.BROADCAST_MAX_SEGMENT_SECONDS || 25),
      signal,
    }), signal),
  ]);
  if (imageResult.status === "rejected") {
    logger.error(
      `Skipping ${imageType} turn for ${channelId}: image generation exhausted retries`,
      "broadcast",
      asError(imageResult.reason),
    );
    if (narrationResult.status === "fulfilled" && narrationResult.value.length > 0) {
      logger.warn(`Discarding lone narration for ${channelId}: image generation failed`, "broadcast");
    }
    return { narration: [] };
  }
  if (narrationResult.status === "rejected" || narrationResult.value.length === 0) {
    logger.warn(
      `Narration unavailable for ${channelId}; releasing image-only turn`,
      "broadcast",
      narrationResult.status === "rejected" ? asError(narrationResult.reason) : undefined,
    );
    return { image: imageResult.value, narration: [] };
  }
  return { image: imageResult.value, narration: narrationResult.value };
}

function slotsWithAssets(input: {
  channelId: string;
  sessionId?: number;
  blockId?: number;
  runId?: string;
  sequence?: number;
  image: GeneratedStoryImage;
  narration: PreparedNarration[];
}): PreparedBroadcastSlot[] {
  const base = input.blockId !== undefined && input.sessionId !== undefined
    ? `channel:${input.channelId}:session:${input.sessionId}:block:${input.blockId}`
    : `channel:${input.channelId}:run:${input.runId}:sequence:${input.sequence}`;
  const narration = input.narration.length > 0 ? input.narration : [undefined];
  return narration.map((item, segmentOrdinal) => {
    const idempotencyPrefix = `${base}:segment:${segmentOrdinal}`;
    return {
      durationSeconds: item?.speech.durationSeconds ?? imageOnlyDuration(),
      idempotencyPrefix,
      slotKey: `${idempotencyPrefix}:slot`,
      ...(input.blockId !== undefined ? { blockId: input.blockId } : {}),
      segmentOrdinal,
      image: toUploadAsset(input.image.buffer, input.image.mimeType, input.image.filename),
      ...(item ? {
        audio: toUploadAsset(item.speech.buffer, item.speech.mimeType, `narration-${segmentOrdinal}.${item.speech.extension}`),
      } : {}),
    };
  });
}

async function generateImageWithFallback(
  description: string,
  channelId: string,
  imageType: "block" | "ambient",
  signal: AbortSignal,
  imageRepresentations: readonly SelectedImageRepresentation[] = [],
): Promise<GeneratedImageWithArchive> {
  try {
    return { image: await generateStoryImageAsset(description, { imageRepresentations, signal }) };
  } catch (cause) {
    logger.warn(
      `Generated image failed for ${channelId}; trying an existing channel image`,
      "broadcast",
      asError(cause),
    );
    signal.throwIfAborted();
    const fallback = await storage.getRandomImage(channelId);
    if (!fallback) throw cause;
    const asset = await fetchArchiveAsset(assertArchiveMediaUrl(fallback, "image"), "image", signal);
    return {
      image: {
        buffer: Buffer.from(await asset.data.arrayBuffer()),
        mimeType: "image/jpeg",
        filename: asset.filename,
      },
      ...(imageType === "block" ? { archiveUrl: fallback } : {}),
    };
  }
}

async function retryGeneration<T>(
  label: string,
  operation: () => Promise<T>,
  signal: AbortSignal,
): Promise<T> {
  let lastError: unknown;
  for (let attempt = 0; attempt < GENERATION_ATTEMPTS; attempt += 1) {
    signal.throwIfAborted();
    try {
      return await operation();
    } catch (cause) {
      if (signal.aborted) throw signal.reason;
      lastError = cause;
      if (attempt === GENERATION_ATTEMPTS - 1) break;
      logger.warn(`${label} attempt ${attempt + 1} failed; retrying`, "broadcast", asError(cause));
      await wait(RETRY_DELAYS_MS[attempt]!, signal);
    }
  }
  throw asError(lastError);
}

function imageOnlyDuration(): number {
  const configured = Number(process.env.BROADCAST_IMAGE_ONLY_DURATION_SECONDS || 15);
  return Number.isFinite(configured) ? Math.max(1, Math.min(30, configured)) : 15;
}

function toUploadAsset(buffer: Buffer, mimeType: string, filename: string): QueueUploadAsset {
  if (buffer.length === 0) throw new Error(`Cannot queue empty ${filename}`);
  return {
    data: new Blob([Uint8Array.from(buffer)], { type: mimeType }),
    filename,
    sha256: crypto.createHash("sha256").update(buffer).digest("hex"),
  };
}

async function fetchArchiveAsset(
  url: string,
  kind: "image" | "audio",
  signal: AbortSignal,
): Promise<QueueUploadAsset> {
  const response = await fetch(url, { signal });
  if (!response.ok) throw new Error(`Archived ${kind} download failed (${response.status})`);
  const buffer = Buffer.from(await response.arrayBuffer());
  const contentType = response.headers.get("content-type") || (kind === "image" ? "image/jpeg" : "audio/wav");
  return toUploadAsset(buffer, contentType, `recovered-${crypto.randomUUID()}.${kind === "image" ? "jpg" : "wav"}`);
}

function assertArchiveMediaUrl(value: string, kind: string): string {
  const url = new URL(value);
  if (url.protocol !== "https:" && (process.env.NODE_ENV === "production" || url.protocol !== "http:")) {
    throw new Error(`${kind} archive URL must use public HTTPS`);
  }
  if (url.username || url.password || url.hash) throw new Error(`${kind} archive URL is not public-safe`);
  return url.toString();
}

function wait(delayMs: number, signal: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    if (signal.aborted) {
      reject(signal.reason);
      return;
    }
    const timer = setTimeout(() => {
      signal.removeEventListener("abort", abort);
      resolve();
    }, delayMs);
    timer.unref?.();
    const abort = () => {
      clearTimeout(timer);
      reject(signal.reason);
    };
    signal.addEventListener("abort", abort, { once: true });
  });
}

function asError(cause: unknown): Error {
  return cause instanceof Error ? cause : new Error(String(cause));
}
