import crypto from "node:crypto";

import type { QueueUploadAsset } from "@portalshq/capability-queue-broadcast";
import type { Block, DeliverySegment, Session } from "@shared/schema";

import { generateStoryBlock } from "../blocks/ai";
import {
  archiveStoryImage,
  generateStoryImageAsset,
  type GeneratedStoryImage,
} from "../image-uploader";
import { logger } from "../logger";
import {
  archiveSpeechBuffer,
  synthesizeNarrationBuffers,
  type SpeechBuffer,
} from "../media/tts-service";
import { storage } from "../storage";

export interface PreparedBroadcastPair {
  durationSeconds: number;
  idempotencyPrefix: string;
  blockId?: number;
  segmentOrdinal: number;
  /** Present after the pair is durably staged at the remote streamer. */
  queuePairId?: string;
  /** Present only while this trusted backend holds completed generated bytes. */
  image?: QueueUploadAsset;
  audio?: QueueUploadAsset;
}

interface GeneratedImageWithArchive {
  image: GeneratedStoryImage;
  archiveUrl?: string;
}

export async function prepareCanonicalBlock(
  channelId: string,
  session: Session,
  previousContext: string,
  signal: AbortSignal,
): Promise<{ block: Block; pairs: PreparedBroadcastPair[] }> {
  signal.throwIfAborted();
  const generated = await generateStoryBlock(channelId, previousContext, false, session.id);
  const generatedImage = await generateImageWithFallback(
    `${generated.title}: ${generated.content.slice(0, 300)}`,
    channelId,
    "block",
    signal,
  );
  const speech = await synthesizeNarrationBuffers(generated.dialogue || generated.content, {
    maxDurationSeconds: Number(process.env.BROADCAST_MAX_SEGMENT_SECONDS || 25),
    signal,
  });
  if (speech.length === 0) throw new Error("Narration produced no delivery segments");

  // Canonical media is archived for replay independently. The streamer never
  // reads these URLs; it receives the finished bytes directly below.
  const imageUrl = generatedImage.archiveUrl
    ?? await archiveStoryImage(generatedImage.image, channelId, "block");
  const archivedAudio = await Promise.all(speech.map(async ({ speech: audio }, ordinal) => ({
    audioUrl: await archiveSpeechBuffer(
      audio,
      `channel-${channelId}-session-${session.id}-${crypto.randomUUID()}-${String(ordinal).padStart(3, "0")}.${audio.extension}`,
    ),
    durationSeconds: audio.durationSeconds,
  })));
  const deliverySegments: DeliverySegment[] = archivedAudio.map((segment, ordinal) => ({
    audioUrl: assertArchiveMediaUrl(segment.audioUrl, "audio"),
    durationSeconds: segment.durationSeconds,
    ordinal,
  }));
  const block = await storage.createBlock({
    channelId,
    sessionId: session.id,
    title: generated.title,
    content: generated.content,
    dialogue: generated.dialogue ?? null,
    imageUrl: assertArchiveMediaUrl(imageUrl, "image"),
    optionA: generated.optionA ?? null,
    optionB: generated.optionB ?? null,
    ttsEnabled: true,
    audioUrl: deliverySegments[0].audioUrl,
    deliverySegments,
    isNotable: false,
  });
  return {
    block,
    pairs: speech.map(({ speech: audio }, ordinal) => pairWithAssets({
      channelId,
      sessionId: session.id,
      blockId: block.id,
      segmentOrdinal: ordinal,
      durationSeconds: audio.durationSeconds,
      image: generatedImage.image,
      audio,
    })),
  };
}

export async function prepareAmbientPair(
  channelId: string,
  previousCanonicalContext: string,
  runId: string,
  sequence: number,
  signal: AbortSignal,
): Promise<PreparedBroadcastPair[]> {
  signal.throwIfAborted();
  const generated = await generateStoryBlock(channelId, previousCanonicalContext, false);
  const generatedImage = await generateImageWithFallback(
    `${generated.title}: ${generated.content.slice(0, 300)}`,
    channelId,
    "ambient",
    signal,
  );
  const speech = await synthesizeNarrationBuffers(generated.dialogue || generated.content, {
    maxDurationSeconds: Number(process.env.BROADCAST_MAX_SEGMENT_SECONDS || 25),
    signal,
  });
  return speech.map(({ speech: audio }, ordinal) => pairWithAssets({
    channelId,
    runId,
    sequence,
    segmentOrdinal: ordinal,
    durationSeconds: audio.durationSeconds,
    image: generatedImage.image,
    audio,
  }));
}

export function pairsFromBlock(block: Block): PreparedBroadcastPair[] {
  const segments = block.deliverySegments ?? (
    block.audioUrl ? [{ audioUrl: block.audioUrl, durationSeconds: 25, ordinal: 0 }] : []
  );
  return segments.map((segment) => ({
    durationSeconds: segment.durationSeconds,
    idempotencyPrefix: segment.queueIdempotencyKey
      ?? `channel:${block.channelId}:session:${block.sessionId}:block:${block.id}:segment:${segment.ordinal}`,
    blockId: block.id,
    segmentOrdinal: segment.ordinal,
    ...(segment.queuePairId ? { queuePairId: segment.queuePairId } : {}),
  }));
}

async function generateImageWithFallback(
  description: string,
  channelId: string,
  imageType: "block" | "ambient",
  signal: AbortSignal,
): Promise<GeneratedImageWithArchive> {
  try {
    return { image: await generateStoryImageAsset(description) };
  } catch (cause) {
    logger.warn(
      `Generated image failed for ${channelId}; trying an existing channel image`,
      "broadcast",
      cause instanceof Error ? cause : new Error(String(cause)),
    );
    const fallback = await storage.getRandomImage(channelId);
    if (!fallback) throw cause;
    const asset = await fetchArchiveAsset(assertArchiveMediaUrl(fallback, "image"), "image", signal);
    return {
      image: {
        buffer: Buffer.from(await asset.data.arrayBuffer()),
        mimeType: "image/jpeg",
        filename: asset.filename,
      },
      ...(imageType === "block" ? { archiveUrl: fallback } : {}),
    };
  }
}

/** Recovery-only: re-upload archived bytes if staging was interrupted before persistence. */
export async function hydrateCanonicalPair(
  block: Block,
  pair: PreparedBroadcastPair,
  signal: AbortSignal,
): Promise<PreparedBroadcastPair> {
  if (!block.imageUrl) throw new Error(`Canonical block ${block.id} has no archived image`);
  const segment = block.deliverySegments?.find((item) => item.ordinal === pair.segmentOrdinal)
    ?? (block.audioUrl ? { audioUrl: block.audioUrl, durationSeconds: pair.durationSeconds, ordinal: pair.segmentOrdinal } : undefined);
  if (!segment?.audioUrl) throw new Error(`Canonical block ${block.id} has no archived audio segment`);
  const [image, audio] = await Promise.all([
    fetchArchiveAsset(assertArchiveMediaUrl(block.imageUrl, "image"), "image", signal),
    fetchArchiveAsset(assertArchiveMediaUrl(segment.audioUrl, "audio"), "audio", signal),
  ]);
  return { ...pair, image, audio };
}

function pairWithAssets(input: {
  channelId: string;
  sessionId?: number;
  blockId?: number;
  runId?: string;
  sequence?: number;
  segmentOrdinal: number;
  durationSeconds: number;
  image: GeneratedStoryImage;
  audio: SpeechBuffer;
}): PreparedBroadcastPair {
  const idempotencyPrefix = input.blockId !== undefined && input.sessionId !== undefined
    ? `channel:${input.channelId}:session:${input.sessionId}:block:${input.blockId}:segment:${input.segmentOrdinal}`
    : `channel:${input.channelId}:run:${input.runId}:sequence:${input.sequence}:segment:${input.segmentOrdinal}`;
  return {
    durationSeconds: input.durationSeconds,
    idempotencyPrefix,
    ...(input.blockId !== undefined ? { blockId: input.blockId } : {}),
    segmentOrdinal: input.segmentOrdinal,
    image: toUploadAsset(input.image.buffer, input.image.mimeType, input.image.filename),
    audio: toUploadAsset(input.audio.buffer, input.audio.mimeType, `narration-${input.segmentOrdinal}.${input.audio.extension}`),
  };
}

function toUploadAsset(buffer: Buffer, mimeType: string, filename: string): QueueUploadAsset {
  if (buffer.length === 0) throw new Error(`Cannot queue empty ${filename}`);
  return {
    data: new Blob([Uint8Array.from(buffer)], { type: mimeType }),
    filename,
    sha256: crypto.createHash("sha256").update(buffer).digest("hex"),
  };
}

async function fetchArchiveAsset(
  url: string,
  kind: "image" | "audio",
  signal: AbortSignal,
): Promise<QueueUploadAsset> {
  const response = await fetch(url, { signal });
  if (!response.ok) throw new Error(`Archived ${kind} download failed (${response.status})`);
  const buffer = Buffer.from(await response.arrayBuffer());
  const contentType = response.headers.get("content-type") || (kind === "image" ? "image/jpeg" : "audio/wav");
  return toUploadAsset(buffer, contentType, `recovered-${crypto.randomUUID()}.${kind === "image" ? "jpg" : "wav"}`);
}

function assertArchiveMediaUrl(value: string, kind: string): string {
  const url = new URL(value);
  if (url.protocol !== "https:" && (process.env.NODE_ENV === "production" || url.protocol !== "http:")) {
    throw new Error(`${kind} archive URL must use public HTTPS`);
  }
  if (url.username || url.password || url.hash) throw new Error(`${kind} archive URL is not public-safe`);
  return url.toString();
}
