-- Migration for High-Performance Ingestion Layer
-- Author: Principal Performance Engineer
-- Date: 2026-02-28

-- 1. Rename existing 'reactions' table to avoid conflict (if it exists)
DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'reactions') THEN
        ALTER TABLE reactions RENAME TO reactions_legacy;
    END IF;
END
$$;

-- 2. Create the main partitioned 'reactions' table
-- Partitioned by RANGE on created_at (Daily partitions)
CREATE TABLE reactions (
    reaction_id BIGINT NOT NULL, -- Snowflake ID or similar, generated by app
    user_id UUID NOT NULL,
    target_id UUID NOT NULL, -- block_id or message_id
    reaction_type SMALLINT NOT NULL, -- Enum mapped to integer
    metadata JSONB DEFAULT '{}'::jsonb, -- Narrative context
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
) PARTITION BY RANGE (created_at);

-- 3. Create initial partitions (Yesterday, Today, Tomorrow)
-- This ensures the system works immediately upon deployment
CREATE TABLE reactions_p20260227 PARTITION OF reactions
    FOR VALUES FROM ('2026-02-27 00:00:00+00') TO ('2026-02-28 00:00:00+00');

CREATE TABLE reactions_p20260228 PARTITION OF reactions
    FOR VALUES FROM ('2026-02-28 00:00:00+00') TO ('2026-03-01 00:00:00+00');

CREATE TABLE reactions_p20260301 PARTITION OF reactions
    FOR VALUES FROM ('2026-03-01 00:00:00+00') TO ('2026-03-02 00:00:00+00');

-- 4. Create BRIN Index on created_at for time-series range scans
-- BRIN is highly efficient for append-only time-ordered data
CREATE INDEX idx_reactions_created_at_brin ON reactions USING BRIN (created_at);

-- 5. Avoid B-Tree indexes on high-cardinality random IDs unless necessary for point lookups.
-- We might need one on target_id later for aggregation queries, but for now we follow specs.

-- 6. Create 'failed_ingestion_log' table for Dead Letter Office (DLO) pattern
CREATE TABLE failed_ingestion_log (
    id SERIAL PRIMARY KEY,
    batch_id UUID NOT NULL,
    error_message TEXT,
    payload JSONB, -- The entire batch of reactions that failed
    failed_at TIMESTAMPTZ DEFAULT NOW(),
    retry_count INT DEFAULT 0,
    status TEXT DEFAULT 'pending' -- pending, replayed, ignored
);

-- 7. Create maintenance function to pre-create partitions
CREATE OR REPLACE FUNCTION maintain_partitions()
RETURNS void AS $$
DECLARE
    tomorrow_date DATE;
    partition_name TEXT;
    start_timestamp TIMESTAMPTZ;
    end_timestamp TIMESTAMPTZ;
BEGIN
    tomorrow_date := CURRENT_DATE + INTERVAL '1 day';
    partition_name := 'reactions_p' || to_char(tomorrow_date, 'YYYYMMDD');
    start_timestamp := date_trunc('day', tomorrow_date);
    end_timestamp := start_timestamp + INTERVAL '1 day';

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = partition_name) THEN
        EXECUTE format(
            'CREATE TABLE %I PARTITION OF reactions FOR VALUES FROM (%L) TO (%L)',
            partition_name, start_timestamp, end_timestamp
        );
        -- Add BRIN index to new partition automatically? (Inherited from parent usually, but verify)
    END IF;
END;
$$ LANGUAGE plpgsql;

-- 8. Extend 'chat' table (messages) if needed
-- Existing: id (serial), channel_id, username, text, session_id, created_at
-- We might want partitioning here too if volume is high (5M+ events/day includes messages).
-- For now, we'll keep it simple but add an index if missing.

CREATE INDEX IF NOT EXISTS idx_chat_created_at_brin ON chat USING BRIN (created_at);
