import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ArrowLeft, BookOpen, HelpCircle } from 'lucide-react';
import { useLocation, Link } from 'wouter';

export default function About() {
  const [_, setLocation] = useLocation();

  return (
    <main className="flex flex-col h-[100dvh] w-full bg-black text-foreground overflow-auto">
      <header className="absolute top-0 inset-x-0 z-30 flex items-center justify-start p-2">
        <Button variant="ghost" size="icon" onClick={() => setLocation('/')}>
          <ArrowLeft className="size-3" />
        </Button>
      </header>

      <div className="container mx-auto max-w-narrow py-6 px-3">
        <h1 className="font-serif text-4xl md:text-5xl text-center text-white/90 tracking-widest uppercase mb-4">
          About The 25th Chapter
        </h1>

        <div className="space-y-3">
          <Card className="bg-white/5 border-white/10 text-white/80">
            <CardHeader>
              <CardTitle className="font-mono text-lg tracking-wider">What is this?</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 font-mono text-sm">
              <p>
                The 25th Chapter is a real-time, interactive, AI-driven fictional story platform where readers vote on choices to progress the story. 
                Content is generated by the configured AI provider (text and 16:9 accompanying images).
              </p>
            </CardContent>
          </Card>
          
          <Card className="bg-white/5 border-white/10 text-white/80">
            <CardHeader>
              <CardTitle className="font-mono text-lg tracking-wider">Learn More</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 font-mono text-sm">
              <Link to="/install">
                <Button variant="outline" className="mt-1.5 mr-2">
                  <BookOpen className="size-2.5 mr-2" />
                  Installation Guide
                </Button>
              </Link>
              <Link href="/upcoming#faq">
                <Button variant="outline" className="mt-1.5">
                  <HelpCircle className="size-2.5 mr-2" />
                  FAQ
                </Button>
              </Link>
            </CardContent>
          </Card>
        </div>
      </div>
    </main>
  );
}
